# Cargo.toml
[package]
name = "ml_library"
version = "0.1.0"
edition = "2021"

[dependencies]
ndarray = "0.15"
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"
nalgebra = "0.32"

[lib]
crate-type = ["cdylib", "rlib"]
name = "ml_library"